export const GET_USER= "GET_USER"
export const GET_SUCCESS ="GET_SUCCESS"
export const GET_FAILED ="GET_FAILED"

export const ADD_USER ="ADD_USER"
export const ADD_SUCCESS ="ADD_SUCCESS"
export const ADD_FAILED ="ADD_FAILED"

export const DELETE_USER ="DELETE_USER"
export const DELETE_SUCCESS ="DELETE_SUCCESS"
export const DELETE_FAILED ="DELETE_FAILED"

export const UPDATE_USER ="UPDATE_USER"
export const UPDATE_SUCCESS ="UPDATE_SUCCESS"
export const UPDATE_FAILED ="UPDATE_FAILED"