export const GET_TO_DOS_REQUEST="GET_TO_DOS_REQUEST"
export const GET_TO_DOS_SUCCESS="GET_TO_DOS_SUCCESS"
export const GET_TO_DOS_FAILED="GET_TO_DOS_FAILED"

export const POST_TO_DOS_REQUEST ="POST_TO_DOS_REQUEST"
export const POST_TO_DOS_SUCCESS ="POST_TO_DOS_SUCCESS"
export const POST_TO_DOS_FAILED ="POST_TO_DOS_FAILED"

export const UPDATE_TO_DOS_REQUEST ="UPDATE_TO_DOS_REQUEST"
export const UPDATE_TO_DOS_SUCCESS ="UPDATE_TO_DOS_SUCCESS"
export const UPDATE_TO_DOS_FAILED ="UPDATE_TO_DOS_FAILED"

export const DELETE_TO_DOS_REQUEST ="DELETE_TO_DOS_REQUEST"
export const DELETE_TO_DOS_SUCCESS ="DELETE_TO_DOS_SUCCESS"
export const DELETE_TO_DOS_FAILED ="DELETE_TO_DOS_FAILED"